name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image (build stage)
        run: docker build -t practice-4-build --target build .

      - name: Run unit tests
        run: docker run --rm practice-4-build go test ./cmd/lb -v

      - name: Run integration tests
        run: docker compose -f docker-compose.yaml -f docker-compose.test.yaml up --exit-code-from test
